"use client";

import { useEffect, useState } from "react";

type Language = "pt" | "en";
type CaseKey = "vale" | "bobs" | "cdb" | "pan" | "oi";
type ProjectCase = { client:string; title:string; award:string; youtube?:string; images:string[]; intro:string; details:Record<string,string> };

const copy = {
  pt:{role:"Diretor de Planejamento e Estratégia com mais de 20 anos de experiência. Já atendeu grandes clientes do mercado brasileiro em diversas categorias. Também é antropólogo e creator.",nav:["Projetos","Experiência","Habilidades","Contato"],selected:"Projetos selecionados",archive:"Outros projetos",archiveIntro:"Uma biblioteca viva, pronta para crescer com novos trabalhos.",brands:"Marcas atendidas",brandsIntro:"Algumas das marcas que fizeram parte da minha trajetória.",experience:"Experiência",experienceIntro:"Mais de duas décadas transformando contexto cultural, comportamento e negócio em estratégia de comunicação.",skills:"Habilidades",contact:"Vamos conversar",contactIntro:"Conte sobre uma oportunidade, um desafio de negócio ou uma colaboração.",linkedIn:"Veja meu LinkedIn",send:"Enviar mensagem",form:["Nome","E-mail","Mensagem"],close:"Fechar projeto",open:"Conheça mais",backTop:"Voltar ao topo",translation:"",previous:"Imagem anterior",next:"Próxima imagem"},
  en:{role:"Planning and Strategy Director with over 20 years of experience. Has worked with major Brazilian clients across multiple categories. Also an anthropologist and creator.",nav:["Projects","Experience","Skills","Contact"],selected:"Selected projects",archive:"More projects",archiveIntro:"A living archive, ready to grow with new work.",brands:"Brands",brandsIntro:"Some of the brands that have been part of my career.",experience:"Experience",experienceIntro:"Over two decades turning cultural context, behavior and business into communication strategy.",skills:"Skills",contact:"Let’s talk",contactIntro:"Tell me about an opportunity, a business challenge or a collaboration.",linkedIn:"View my LinkedIn",send:"Send message",form:["Name","Email","Message"],close:"Close project",open:"Discover more",backTop:"Back to top",translation:"ENGLISH TRANSLATION DRAFT — PENDING APPROVAL",previous:"Previous image",next:"Next image"},
};

const cases:{pt:Record<CaseKey,ProjectCase>;en:Record<CaseKey,ProjectCase>} = {
  pt:{
    vale:{client:"VALE",title:"Amazônia para sempre",award:"Leão de Prata em Cannes",youtube:"https://www.youtube.com/embed/69wX6HZImHw",images:[],intro:"Como a Vale transformou quatro décadas de preservação da Amazônia em uma experiência cultural criada por quem mantém a floresta viva.",details:{Briefing:"Fortalecer o reconhecimento da Vale por sua atuação histórica na preservação da Amazônia, valorizando também a cultura local e os povos originários.",Objetivo:"Construir uma conexão legítima entre a Vale e a causa amazônica em um ano no qual a COP30 colocaria a floresta no centro das atenções mundiais.",Insight:"Preservar a Amazônia também significa manter vivas as histórias, os saberes e as culturas das pessoas que cuidam da floresta.",Ideia:"Amazônia Live: fazer da vitória-régia um símbolo de renascimento da cultura, das histórias e dos saberes dos povos originários, transformando suas pétalas em forma de celebração.",Execução:"Celebração em vários formatos: um show, um festival amazônico, campanha em digital, OOH, live experience e um almanaque artesanal que reuniu histórias, ilustrações e rituais, levando os saberes da Amazônia para além da floresta.",Resultados:"O projeto ampliou a conexão cultural e humana da Vale com a Amazônia, foi a experiência mais lembrada do The Town, elevou a taxa de reputação da marca e conquistou um Leão de Prata no Cannes Lions."}},
    bobs:{client:"BOB’S",title:"OAB",award:"",images:["./cases/bobs-oab/board-effie-apoio.jpg"],intro:"Como o Bob’s entrou na briga dos gigantes e transformou uma disputa sobre cópia em defesa pública do Milk Shake original.",details:{Briefing:"Entrar em uma conversa monopolizada por Burger King e McDonald’s, mesmo com um investimento mais de 20 vezes menor que o líder da categoria.",Objetivo:"Transformar a disputa entre os concorrentes em relevância cultural para Bob’s, reforçando sua associação histórica com o Milk Shake original.",Insight:"Se a categoria falava de cópia, Bob’s tinha jurisprudência: há décadas, seu Milk Shake sabia o que era ser copiado.",Ideia:"Criar a OAB — Ordem dos Advogados do Bob’s — para transformar o humor jurídico em defesa pública do original.",Execução:"Uma nota de solidariedade irônica convocou advogados, fãs e consumidores a defenderem o Milk Shake original. A brincadeira ganhou os comentários, foi amplificada por mídia paga e chegou às lojas, com honorários cobrados em Milk Shake.",Resultados:"A ação alcançou 1,4 milhão de views e 80,4 mil interações, com engajamento 21 vezes superior à média da marca e crescimento de 470% em novos seguidores. Também gerou 6.947 visitas ao perfil e repercussão espontânea na imprensa."}},
    cdb:{client:"BANCO PAN",title:"CDB da Bruna",award:"Finalista Effie Davi Golias",youtube:"https://www.youtube.com/embed/4BRS--L2MHU",images:[],intro:"Como o PAN transformou uma sigla do mercado financeiro em diferentes possibilidades para realizar sonhos.",details:{Briefing:"Apresentar o CDB do PAN e fortalecer a percepção do banco como uma instituição digital completa, que oferece investimentos além de crédito.",Objetivo:"Mostrar que investir em CDB pode ser uma forma simples, segura e acessível de guardar dinheiro para realizar diferentes projetos de vida.",Insight:"As pessoas não investem apenas para fazer o dinheiro render: elas guardam recursos para conquistar algo que importa.",Ideia:"Dar novos significados à sigla CDB, transformando-a em sonhos como “Curso de Balé”, “Cozinha da Bárbara” e “Cantinho do Bebê” — até chegar ao “Comercial da Bruna”.",Execução:"Bruna Marquezine apresentou os diferentes significados de CDB em um filme bem-humorado, desdobrado em mídia exterior, redes sociais e canais digitais. A comunicação mostrou que era possível começar com pouco, em poucos cliques.",Resultados:"A campanha nacional tornou o CDB mais tangível e aproximou o território de investimentos do público do PAN. Houve aumento recorde no investimento em CDB do Banco PAN, aumento de buscas pela marca e aumento da abertura de contas."}},
    pan:{client:"BANCO PAN",title:"Reposicionamento",award:"Finalista Effie",youtube:"https://www.youtube.com/embed/tYXgz22inWw",images:[],intro:"Como o PAN provocou os brasileiros a repensarem sua relação com os bancos e passou a ser reconhecido como uma instituição digital completa.",details:{Briefing:"O PAN, que sempre foi visto como um banco de crédito, precisava mostrar que tinha diversas soluções em um só lugar, que nem um bancão.",Objetivo:"Ampliar a percepção do PAN como um banco digital completo e relevante para diferentes momentos da vida financeira.",Insight:"Se as pessoas parassem para repensar sua relação com os bancos, perceberiam que poderiam encontrar tudo o que precisam no PAN.",Ideia:"“Para, Pensa e PAN”: um novo posicionamento para convidar as pessoas a reconsiderarem suas escolhas financeiras.",Execução:"Bruna Marquezine e Luciano Huck revisitaram momentos decisivos de suas trajetórias, com apoio de inteligência artificial. A campanha ganhou TV, cinema, redes sociais, metrô, mídia exterior e ações sincronizadas no YouTube.",Resultados:"Mais de 100 milhões de pessoas impactadas, +17 pontos em awareness, +13 pontos em preferência, pico de 62% nas buscas e crescimento recorde de 65% em relação ao ano anterior, além de recorde nas solicitações de cartões e avanço no uso do Pix."}},
    oi:{client:"Oi",title:"Oi Black Friday",award:"",youtube:"https://www.youtube.com/embed/KhcVParXDeE",images:[],intro:"Como a Oi Fibra invadiu as ofertas dos maiores varejistas para transformar o desejo por novos dispositivos em recorde histórico de vendas.",details:{Briefing:"Destacar Oi Fibra durante a Black Friday, período dominado pelas grandes ofertas do varejo.",Objetivo:"Aproveitar o desejo por novos dispositivos para impulsionar as vendas de Oi Fibra.",Insight:"Todo dispositivo desejado na Black Friday precisa de uma conexão rápida e estável para entregar seu potencial.",Ideia:"“Oi Fibra invadiu sua Black Friday”: usar as ofertas mais desejadas do varejo como porta de entrada para apresentar Oi Fibra.",Execução:"Com Rafael Portugal e Júlia Rabello, a marca invadiu comerciais, marketplaces, redes sociais, unboxings e comunicações de grandes varejistas, do pré ao pós-Black Friday.",Resultados:"Com menor investimento, Oi Fibra impulsionou suas vendas e superou as metas históricas da companhia em novembro e dezembro."}},
  },
  en:{
    vale:{client:"VALE",title:"Amazon Forever",award:"Cannes Silver Lion",youtube:"https://www.youtube.com/embed/69wX6HZImHw",images:[],intro:"How Vale transformed four decades of Amazon preservation into a cultural experience created by the people who keep the forest alive.",details:{Briefing:"Strengthen recognition of Vale’s longstanding work to preserve the Amazon while also valuing local culture and Indigenous peoples.",Objective:"Build a legitimate connection between Vale and the Amazon cause in a year when COP30 would place the forest at the center of global attention.",Insight:"Preserving the Amazon also means keeping alive the stories, knowledge and cultures of the people who care for the forest.",Idea:"Amazônia Live: turn the giant water lily into a symbol of the rebirth of Indigenous culture, stories and knowledge, transforming its petals into a form of celebration.",Execution:"A celebration across formats: a concert, an Amazonian festival, digital and OOH campaigns, a live experience and a handcrafted almanac bringing together stories, illustrations and rituals to carry Amazonian knowledge beyond the forest.",Results:"The project deepened Vale’s cultural and human connection with the Amazon, became the most remembered experience at The Town, improved the brand’s reputation score and won a Silver Lion at Cannes Lions."}},
    bobs:{client:"BOB’S",title:"OAB",award:"",images:["./cases/bobs-oab/board-effie-apoio.jpg"],intro:"How Bob’s entered a battle between category giants and turned a dispute about copying into a public defense of the original Milk Shake.",details:{Briefing:"Enter a conversation dominated by Burger King and McDonald’s despite an investment more than 20 times smaller than the category leader’s.",Objective:"Turn the competitors’ dispute into cultural relevance for Bob’s, reinforcing its historic association with the original Milk Shake.",Insight:"If the category was talking about copying, Bob’s had precedent: for decades, its Milk Shake had known what it meant to be copied.",Idea:"Create OAB — the Bob’s Bar Association — turning legal humor into a public defense of the original.",Execution:"An ironic statement of solidarity invited lawyers, fans and consumers to defend the original Milk Shake. The joke took over the comments, was amplified through paid media and reached stores, with legal fees charged in Milk Shakes.",Results:"The activation achieved 1.4 million views and 80,400 interactions, with engagement 21 times above the brand average and 470% growth in new followers. It also generated 6,947 profile visits and earned spontaneous press coverage."}},
    cdb:{client:"BANCO PAN",title:"Bruna’s CDB",award:"Effie David vs. Goliath Finalist",youtube:"https://www.youtube.com/embed/4BRS--L2MHU",images:[],intro:"How PAN turned a financial-market acronym into different possibilities for making dreams come true.",details:{Briefing:"Introduce PAN’s CDB investment product and strengthen perceptions of the bank as a complete digital institution offering investments beyond credit.",Objective:"Show that investing in a CDB can be a simple, safe and accessible way to save money for different life goals.",Insight:"People do not invest only to make money grow; they set resources aside to achieve something that matters.",Idea:"Give the acronym CDB new meanings by turning it into dreams such as ‘Ballet Course,’ ‘Barbara’s Kitchen’ and ‘Baby’s Corner’ — culminating in ‘Bruna’s Commercial.’",Execution:"Bruna Marquezine presented the different meanings of CDB in a humorous film extended across out-of-home media, social networks and digital channels. The communication showed that people could start with a small amount in just a few clicks.",Results:"The national campaign made CDBs more tangible and brought investment closer to PAN’s audience. It drove record growth in CDB investment at Banco PAN, increased brand searches and increased account openings."}},
    pan:{client:"BANCO PAN",title:"Brand Repositioning",award:"Effie Finalist",youtube:"https://www.youtube.com/embed/tYXgz22inWw",images:[],intro:"How PAN prompted Brazilians to rethink their relationship with banks and became recognized as a complete digital financial institution.",details:{Briefing:"PAN had long been perceived as a credit-focused bank and needed to show that it offered a full range of solutions in one place, just like a major bank.",Objective:"Broaden perceptions of PAN as a complete digital bank, relevant to different moments in people’s financial lives.",Insight:"If people stopped to rethink their relationship with banks, they would realize they could find everything they needed at PAN.",Idea:"‘Stop, Think and PAN’: a new positioning designed to invite people to reconsider their financial choices.",Execution:"Bruna Marquezine and Luciano Huck revisited pivotal moments in their careers with the support of artificial intelligence. The campaign ran across TV, cinema, social media, the subway, out-of-home media and synchronized YouTube activations.",Results:"More than 100 million people reached, a 17-point increase in awareness, a 13-point increase in preference, a 62% peak in searches and record 65% year-over-year growth, alongside record card applications and increased Pix usage."}},
    oi:{client:"Oi",title:"Oi Black Friday",award:"",youtube:"https://www.youtube.com/embed/KhcVParXDeE",images:[],intro:"How Oi Fibra took over major retailers’ promotions to turn the desire for new devices into record-breaking sales.",details:{Briefing:"Make Oi Fibra stand out during Black Friday, a period dominated by major retail promotions.",Objective:"Leverage consumers’ desire for new devices to drive Oi Fibra sales.",Insight:"Every device people want on Black Friday needs a fast, stable connection to deliver its full potential.",Idea:"‘Oi Fibra took over your Black Friday’: use the most sought-after retail deals as an entry point to introduce Oi Fibra.",Execution:"Featuring Rafael Portugal and Júlia Rabello, the brand took over commercials, marketplaces, social media, unboxings and communications from major retailers before, during and after Black Friday.",Results:"With a smaller investment, Oi Fibra boosted sales and surpassed the company’s all-time targets in November and December."}},
  },
};

const experience={pt:[["Artplan","Diretor de Planejamento","2024 — atualidade"],["Grupo Dreamers","Gerente de Planejamento","2021 — 2024"],["Artplan","Supervisor de Planejamento","2019 — 2020"],["BTG Agência","Head de criatividade e estratégia","2017 — 2018"]],en:[["Artplan","Planning Director","2024 — present"],["Grupo Dreamers","Planning Manager","2021 — 2024"],["Artplan","Planning Supervisor","2019 — 2020"],["BTG Agência","Head of Creative and Strategy","2017 — 2018"]]};

const archiveProjects:string[]=[];
const primaryBrands=[["Banco PAN","./client-logos/primary/banco-pan.png"],["Oi","./client-logos/primary/oi.png"],["Bob's","./client-logos/primary/bobs.webp"],["Vale","./client-logos/primary/vale.webp"],["YDUQS","./client-logos/primary/yduqs.webp"],["Baruel","./client-logos/primary/baruel.webp"]];
const secondaryBrands=[["Petrobras","./client-logos/secondary/petrobras.gif"],["Aegea","./client-logos/secondary/aegea.png"],["Localiza","./client-logos/secondary/localiza.webp"],["Amil","./client-logos/secondary/amil.png"],["Cultura Inglesa","./client-logos/secondary/cultura-inglesa.webp"],["IDOMED","./client-logos/secondary/idomed.png"],["Ibmec","./client-logos/secondary/ibmec.webp"],["Brasilcap","./client-logos/secondary/brasilcap.png"],["Submarino","./client-logos/secondary/submarino.png"],["Enel","./client-logos/secondary/enel.png"],["Américas Serviços Médicos","./client-logos/secondary/americas.svg"],["Zoop","./client-logos/secondary/zoop.png"],["Vizcaya Cosméticos","./client-logos/secondary/vizcaya.png"],["Alfaparf Milano","./client-logos/secondary/alfaparf.png"],["GNT","./client-logos/secondary/gnt.png"],["Viva","./client-logos/secondary/viva.webp"],["Rock in Rio","./client-logos/secondary/rock-in-rio.png"],["CNseg","./client-logos/secondary/cnseg.png"],["Duloren","./client-logos/secondary/duloren.webp"],["Fundação Roberto Marinho","./client-logos/secondary/fundacao-roberto-marinho.png"]];

function ProjectMedia({project,modal=false,slide=0}:{project:ProjectCase;modal?:boolean;slide?:number}){
  if(project.youtube) return <iframe src={`${project.youtube}?rel=0`} title={`${project.client} — ${project.title}`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/>;
  return <img className={modal?"modal-case-image":"case-cover"} src={project.images[slide]} alt={`${project.client} — ${project.title}`} />;
}

export default function Home(){
  const[language,setLanguage]=useState<Language>("pt");const[activeCase,setActiveCase]=useState<CaseKey|null>(null);const[slide,setSlide]=useState(0);const t=copy[language];const localizedCases=cases[language];
  useEffect(()=>{document.documentElement.lang=language==="pt"?"pt-BR":"en";document.body.style.overflow=activeCase?"hidden":"";return()=>{document.body.style.overflow=""}},[activeCase,language]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>e.key==="Escape"&&setActiveCase(null);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  const openCase=(key:CaseKey)=>{setSlide(0);setActiveCase(key)};const entries=Object.entries(localizedCases) as [CaseKey,ProjectCase][];const selected=activeCase?localizedCases[activeCase]:null;
  return <main>
    <header className="site-header"><a className="mini-brand" href="#top" aria-label="Yuri Alcantara — início"><span className="mark-crop"><img src="./asterisco-amarelo.png" alt=""/></span><span>yuri <b>ALCANTARA</b></span></a><nav aria-label="Navegação principal">{t.nav.map((item,i)=><a key={item} href={`#${["projetos","experiencia","habilidades","contato"][i]}`}>{item}</a>)}</nav><div className="language-toggle" role="group" aria-label="Idioma"><span className={language==="pt"?"active":""}>PT</span><button type="button" className={language==="en"?"switched":""} onClick={()=>setLanguage(language==="pt"?"en":"pt")} aria-label="Alternar entre português e inglês" aria-pressed={language==="en"}><i/></button><span className={language==="en"?"active":""}>EN</span></div></header>
    <section className="hero" id="top"><div className="hero-image" aria-hidden="true"/><div className="hero-shade"/><div className="hero-content"><span className="hero-mark mark-crop"><img src="./asterisco-amarelo.png" alt=""/></span><h1><em>yuri</em><span>ALCANTARA</span></h1><p>{t.role}</p><a className="scroll-cue" href="#projetos">{language==="pt"?"Conheça o trabalho":"Explore the work"}<b>↓</b></a></div></section>
    <section className="projects-section" id="projetos"><div className="section-heading"><span className="eyebrow">01 — PORTFÓLIO</span><h2>{t.selected}</h2></div>{t.translation&&<p className="translation-notice">{t.translation}</p>}<div className="featured-list">{entries.map(([key,p],i)=><article className={`featured-card ${i%2?"yellow":"violet"}`} key={key}><div className="case-video"><span className="project-number">{String(i+1).padStart(2,"0")}</span><ProjectMedia project={p}/></div><div className="project-summary"><span className="draft-label">{p.award||p.client}</span><small className="client-name">{p.client}</small><h3>{p.title}</h3><p>{p.intro}</p><dl>{Object.entries(p.details).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button className="text-link" onClick={()=>openCase(key)}>{t.open} ↗</button></div></article>)}</div></section>
    {archiveProjects.length>0&&<section className="archive-section"><div className="section-heading compact"><span className="eyebrow">02 — ARQUIVO</span><h2>{t.archive}</h2><p>{t.archiveIntro}</p></div></section>}
    <section className="brands-section" id="marcas"><div className="section-heading compact light"><span className="eyebrow">03 — TRAJETÓRIA</span><h2>{t.brands}</h2><p>{t.brandsIntro}</p></div><div className="brand-tier"><div className="tier-heading"><span>{language==="pt"?"Contas lideradas":"Accounts led"}</span><small>{language==="pt"?"Maior envolvimento estratégico":"Deeper strategic involvement"}</small></div><div className="primary-brand-grid">{primaryBrands.map(([name,src])=><div className="brand-card primary-brand" key={name}><img src={src} alt={`Logo ${name}`}/></div>)}</div></div><div className="brand-tier secondary-tier"><div className="tier-heading"><span>{language==="pt"?"Outras marcas atendidas":"Other brands"}</span><small>{language==="pt"?"Experiência em diferentes categorias":"Experience across categories"}</small></div><div className="secondary-brand-grid">{secondaryBrands.map(([name,src])=><div className="brand-card secondary-brand" key={name}><img src={src} alt={`Logo ${name}`}/></div>)}</div></div></section>
    <section className="profile-section" id="experiencia"><div className="profile-photo"><img src="./yuri-portrait.png" alt="Retrato de Yuri Alcantara"/></div><div className="profile-copy"><span className="eyebrow">04 — EXPERIÊNCIA</span><h2>{t.experience}</h2><p className="large-copy">{t.experienceIntro}</p><div className="experience-list">{experience[language].map(([company,role,period])=><article key={`${company}-${period}`}><strong>{company}</strong><span>{role}</span><time>{period}</time></article>)}</div><a className="button secondary" href="https://www.linkedin.com/in/yuri-alcantara/" target="_blank" rel="noreferrer">{t.linkedIn} ↗</a></div></section>
    <section className="skills-section" id="habilidades"><div className="section-heading compact light"><span className="eyebrow">05 — REPERTÓRIO</span><h2>{t.skills}</h2></div><div className="skill-cloud">{["Planejamento estratégico","Estratégia de marca","Pesquisa","Cultura","Comportamento","Consumer insights","Consultoria","Antropologia","Storytelling"].map(skill=><span key={skill}>{skill}</span>)}</div></section>
    <section className="contact-section" id="contato"><div className="contact-intro"><span className="contact-mark mark-crop"><img src="./asterisco-amarelo.png" alt=""/></span><span className="eyebrow">06 — CONTATO</span><h2>{t.contact}</h2><p>{t.contactIntro}</p></div><form action="mailto:eu.yurialcantara@gmail.com" method="post" encType="text/plain"><label>{t.form[0]}<input name="name" autoComplete="name" required/></label><label>{t.form[1]}<input name="email" type="email" autoComplete="email" required/></label><label>{t.form[2]}<textarea name="message" rows={5} required/></label><button className="button" type="submit">{t.send} ↗</button></form></section>
    <footer><span>© 2026 Yuri Alcantara</span><a href="#top">{t.backTop} ↑</a></footer>
    {selected&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`${selected.client} — ${selected.title}`} onMouseDown={e=>e.target===e.currentTarget&&setActiveCase(null)}><div className="noise"/><article className="project-modal"><button className="modal-close" onClick={()=>setActiveCase(null)} aria-label={t.close}>×</button><div className="modal-media"><ProjectMedia project={selected} modal slide={slide}/>{selected.images.length>1&&<div className="carousel-controls"><button onClick={()=>setSlide((slide-1+selected.images.length)%selected.images.length)} aria-label={t.previous}>←</button><span>{slide+1} / {selected.images.length}</span><button onClick={()=>setSlide((slide+1)%selected.images.length)} aria-label={t.next}>→</button></div>}</div><div className="modal-copy"><span className="draft-label">{selected.award||selected.client}</span><small className="client-name">{selected.client}</small><h2>{selected.title}</h2><p>{selected.intro}</p><dl>{Object.entries(selected.details).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></article></div>}
  </main>;
}
